services: 
  gateway: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ReverseProxy__Clusters__sample-backend__Destinations__sample-backend-primary__Address: http://sample-backend:8080/
    depends_on:
      - sample-backend
  
  sample-backend:
    build:
      context: .
      dockerfile: src/RateShield.SampleBackend/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080